#ifndef STREAM_DECK_SETTINGS_H
#define STREAM_DECK_SETTINGS_H

#define STREAM_DECK_SETTINGS_NAME	"StreamDeckPlugin"
#define STREAM_DECK_SETTINGS_PORT_NAME	"Port"
#define STREAM_DECK_DEFAULT_PORT	8080

#endif // STREAM_DECK_SETTINGS_H